2025-05-15 10:38:55,568 ERROR Invalid HTTP_HOST header: '10.0.2.2:8000'. You may need to add '10.0.2.2' to ALLOWED_HOSTS. /Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/core/handlers/exception.py
Traceback (most recent call last):
  File "/Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '10.0.2.2:8000'. You may need to add '10.0.2.2' to ALLOWED_HOSTS.
2025-05-15 14:06:40,740 ERROR Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS. /Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/core/handlers/exception.py
Traceback (most recent call last):
  File "/Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
2025-05-15 14:06:41,139 ERROR Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS. /Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/core/handlers/exception.py
Traceback (most recent call last):
  File "/Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
2025-05-15 14:06:42,187 ERROR Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS. /Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/core/handlers/exception.py
Traceback (most recent call last):
  File "/Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
2025-05-15 14:06:42,367 ERROR Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS. /Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/core/handlers/exception.py
Traceback (most recent call last):
  File "/Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
2025-05-15 14:06:43,140 ERROR Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS. /Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/core/handlers/exception.py
Traceback (most recent call last):
  File "/Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
2025-05-15 14:06:43,357 ERROR Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS. /Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/core/handlers/exception.py
Traceback (most recent call last):
  File "/Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
2025-05-15 14:06:45,477 ERROR Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS. /Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/core/handlers/exception.py
Traceback (most recent call last):
  File "/Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
2025-05-15 14:06:45,681 ERROR Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS. /Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/core/handlers/exception.py
Traceback (most recent call last):
  File "/Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
2025-05-15 14:06:52,582 ERROR Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS. /Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/core/handlers/exception.py
Traceback (most recent call last):
  File "/Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
2025-05-15 14:06:52,713 ERROR Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS. /Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/core/handlers/exception.py
Traceback (most recent call last):
  File "/Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/Users/3dbody/iOSCode/xyqwebsite/djangoenv/lib/python3.13/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
